-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ebentos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ebentos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ebentos` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ebentos` ;

-- -----------------------------------------------------
-- Table `ebentos`.`DEPARTAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`DEPARTAMENTO` (
  `DEPARTAMENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DEPARTAMENTO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`PROVINCIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`PROVINCIA` (
  `PROVINCIA_ID` INT NOT NULL AUTO_INCREMENT,
  `DEPARTAMENTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PROVINCIA_ID`),
  INDEX `fk_PROVINCIAS_DEPARTAMENTOS1_idx` (`DEPARTAMENTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PROVINCIAS_DEPARTAMENTOS1`
    FOREIGN KEY (`DEPARTAMENTO_ID`)
    REFERENCES `ebentos`.`DEPARTAMENTO` (`DEPARTAMENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`DISTRITO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`DISTRITO` (
  `DISTRITO_ID` INT NOT NULL AUTO_INCREMENT,
  `PROVINCIA_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DISTRITO_ID`),
  INDEX `fk_DISTRITOS_PROVINCIAS1_idx` (`PROVINCIA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DISTRITOS_PROVINCIAS1`
    FOREIGN KEY (`PROVINCIA_ID`)
    REFERENCES `ebentos`.`PROVINCIA` (`PROVINCIA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`ROL` (
  `ROL_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ROL_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`USUARIO` (
  `USUARIO_ID` INT NOT NULL AUTO_INCREMENT,
  `ROL_ID` INT NOT NULL,
  `TELEFONO` VARCHAR(9) NOT NULL,
  `EMAIL` VARCHAR(100) NOT NULL,
  `CONTRASENHA` VARCHAR(100) NOT NULL,
  `ACTIVO` TINYINT NOT NULL,
  `CODIGO_RESETEO` VARCHAR(6) NULL,
  `EXPIRACION_CODIGO` DATETIME NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  INDEX `fk_USUARIO_ROL1_idx` (`ROL_ID` ASC) VISIBLE,
  CONSTRAINT `fk_USUARIO_ROL1`
    FOREIGN KEY (`ROL_ID`)
    REFERENCES `ebentos`.`ROL` (`ROL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`PUNTOVENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`PUNTOVENTA` (
  `PUNTOVENTA_ID` INT NOT NULL AUTO_INCREMENT,
  `DISTRITO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(45) NOT NULL,
  `DIRECCION` VARCHAR(45) NOT NULL,
  `ACTIVO` TINYINT NOT NULL,
  PRIMARY KEY (`PUNTOVENTA_ID`),
  INDEX `fk_PUNTOVENTA_DISTRITO1_idx` (`DISTRITO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PUNTOVENTA_DISTRITO1`
    FOREIGN KEY (`DISTRITO_ID`)
    REFERENCES `ebentos`.`DISTRITO` (`DISTRITO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`GESTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`GESTOR` (
  `USUARIO_ID` INT NOT NULL,
  `USUARIO_CREADOR_ID` INT NULL,
  `PUNTOVENTA_ID` INT NULL,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  INDEX `fk_GESTOR_USUARIO1_idx` (`USUARIO_CREADOR_ID` ASC) VISIBLE,
  INDEX `fk_GESTOR_PUNTOVENTA1_idx` (`PUNTOVENTA_ID` ASC) VISIBLE,
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  CONSTRAINT `fk_GESTOR_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `ebentos`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GESTOR_USUARIO1`
    FOREIGN KEY (`USUARIO_CREADOR_ID`)
    REFERENCES `ebentos`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GESTOR_PUNTOVENTA1`
    FOREIGN KEY (`PUNTOVENTA_ID`)
    REFERENCES `ebentos`.`PUNTOVENTA` (`PUNTOVENTA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`LOCAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`LOCAL` (
  `LOCAL_ID` INT NOT NULL AUTO_INCREMENT,
  `DISTRITO_ID` INT NOT NULL,
  `GESTOR_USUARIO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `DIRECCION` VARCHAR(170) NOT NULL,
  `FOTO` VARCHAR(30) NOT NULL,
  `DNI_PROPIETARIO` VARCHAR(8) NOT NULL,
  `NOMBRE_COMPLETO_PROPIETARIO` VARCHAR(100) NOT NULL,
  `DNI_RESPONSABLE` VARCHAR(8) NOT NULL,
  `NOMBRE_COMPLETO_RESPONSABLE` VARCHAR(100) NOT NULL,
  `TELEFONO_CONTACTO1` VARCHAR(9) NOT NULL,
  `TELEFONO_CONTACTO2` VARCHAR(9) NULL,
  `CORREO_CONTACTO` VARCHAR(45) NOT NULL,
  `AFORO` INT NOT NULL,
  `TIPO_LOCAL` ENUM('BAR', 'CAMPO', 'ESTADIO', 'TEATRO') NOT NULL,
  `ESTADO` ENUM('PENDIENTE', 'ACTIVO', 'DE_BAJA') NOT NULL,
  PRIMARY KEY (`LOCAL_ID`),
  INDEX `fk_LOCALES_DISTRITOS1_idx` (`DISTRITO_ID` ASC) VISIBLE,
  INDEX `fk_LOCALES_GESTOR1_idx` (`GESTOR_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_LOCALES_DISTRITOS1`
    FOREIGN KEY (`DISTRITO_ID`)
    REFERENCES `ebentos`.`DISTRITO` (`DISTRITO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LOCALES_GESTOR1`
    FOREIGN KEY (`GESTOR_USUARIO_ID`)
    REFERENCES `ebentos`.`GESTOR` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`CATEGORIA_EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`CATEGORIA_EVENTO` (
  `CATEGORIA_EVENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CATEGORIA_EVENTO_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`EVENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`EVENTO` (
  `EVENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `LOCAL_ID` INT NOT NULL,
  `GESTOR_USUARIO_ID` INT NOT NULL,
  `CATEGORIA_EVENTO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(100) NOT NULL,
  `DESCRIPCION` VARCHAR(350) NOT NULL,
  `POSTER` VARCHAR(30) NOT NULL,
  `FECHA_HORARIO_INICIO` DATETIME NOT NULL,
  `DURACION_ESTIMADA` INT NOT NULL,
  `COSTO_TOTAL` DOUBLE NOT NULL,
  `VISITAS` INT NOT NULL,
  PRIMARY KEY (`EVENTO_ID`),
  INDEX `fk_EVENTOS_LOCALES1_idx` (`LOCAL_ID` ASC) VISIBLE,
  INDEX `fk_EVENTOS_GESTOR1_idx` (`GESTOR_USUARIO_ID` ASC) VISIBLE,
  INDEX `fk_EVENTO_CATEGORIA_EVENTO1_idx` (`CATEGORIA_EVENTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_EVENTOS_LOCALES1`
    FOREIGN KEY (`LOCAL_ID`)
    REFERENCES `ebentos`.`LOCAL` (`LOCAL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTOS_GESTOR1`
    FOREIGN KEY (`GESTOR_USUARIO_ID`)
    REFERENCES `ebentos`.`GESTOR` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EVENTO_CATEGORIA_EVENTO1`
    FOREIGN KEY (`CATEGORIA_EVENTO_ID`)
    REFERENCES `ebentos`.`CATEGORIA_EVENTO` (`CATEGORIA_EVENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`SOLICITUD`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`SOLICITUD` (
  `LOCAL_ID` INT NOT NULL,
  `EVENTO_ID` INT NOT NULL,
  `JUSTIFICACION` VARCHAR(200) NULL,
  `ESTADO` ENUM('APROBADO', 'EN_REVISION', 'RECHAZADO') NOT NULL,
  INDEX `fk_SOLICITUDES_LOCALES1_idx` (`LOCAL_ID` ASC) VISIBLE,
  INDEX `fk_SOLICITUDES_EVENTOS1_idx` (`EVENTO_ID` ASC) VISIBLE,
  PRIMARY KEY (`LOCAL_ID`, `EVENTO_ID`),
  CONSTRAINT `fk_SOLICITUDES_LOCALES1`
    FOREIGN KEY (`LOCAL_ID`)
    REFERENCES `ebentos`.`LOCAL` (`LOCAL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SOLICITUDES_EVENTOS1`
    FOREIGN KEY (`EVENTO_ID`)
    REFERENCES `ebentos`.`EVENTO` (`EVENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`ZONA` (
  `ZONA_ID` INT NOT NULL AUTO_INCREMENT,
  `LOCAL_ID` INT NOT NULL,
  `EVENTO_ID` INT NOT NULL,
  `CAPACIDAD_TOTAL` INT NOT NULL,
  `TIPO_ZONA` VARCHAR(30) NOT NULL,
  `LETRA_ZONA` VARCHAR(1) NOT NULL,
  `ACTIVO` TINYINT NOT NULL,
  `CANTIDAD_ENTRADAS_DISPONIBLES` INT NOT NULL,
  `PRECIO_UNITARIO` DOUBLE NOT NULL,
  `MONTO_TOTAL_RECAUDADO` DOUBLE NOT NULL,
  PRIMARY KEY (`ZONA_ID`),
  INDEX `fk_ZONAS_LOCALES1_idx` (`LOCAL_ID` ASC) VISIBLE,
  INDEX `fk_ZONA_EVENTO1_idx` (`EVENTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ZONAS_LOCALES1`
    FOREIGN KEY (`LOCAL_ID`)
    REFERENCES `ebentos`.`LOCAL` (`LOCAL_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZONA_EVENTO1`
    FOREIGN KEY (`EVENTO_ID`)
    REFERENCES `ebentos`.`EVENTO` (`EVENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`DESCUENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`DESCUENTO` (
  `DESCUENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `GESTOR_USUARIO_ID` INT NOT NULL,
  `NOMBRE` VARCHAR(70) NOT NULL,
  `TIPO_DESCUENTO` ENUM('GLOBAL', 'POR_CANJE') NOT NULL,
  `VALOR_PORCENTAJE` INT NOT NULL,
  `FECHA_HORA_INICIO` DATETIME NOT NULL,
  `FECHA_HORA_FIN` DATETIME NOT NULL,
  `COSTO_PUNTOS` INT NULL,
  PRIMARY KEY (`DESCUENTO_ID`),
  INDEX `fk_DESCUENTO_GESTOR1_idx` (`GESTOR_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DESCUENTO_GESTOR1`
    FOREIGN KEY (`GESTOR_USUARIO_ID`)
    REFERENCES `ebentos`.`GESTOR` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`ASIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`ASIENTO` (
  `ASIENTO_ID` INT NOT NULL AUTO_INCREMENT,
  `ZONA_ID` INT NOT NULL,
  `ENTRADA_ID` INT NULL,
  `FILA` VARCHAR(2) NOT NULL,
  `COLUMNA` INT NOT NULL,
  `PISO` INT NOT NULL,
  `OCUPADO` TINYINT NOT NULL,
  PRIMARY KEY (`ASIENTO_ID`),
  INDEX `fk_ASIENTO_ZONA1_idx` (`ZONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ASIENTO_ZONA1`
    FOREIGN KEY (`ZONA_ID`)
    REFERENCES `ebentos`.`ZONA` (`ZONA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`CLIENTE` (
  `USUARIO_ID` INT NOT NULL,
  `PUNTOS_ACUMULADOS` INT NOT NULL DEFAULT 0,
  `PUNTOS_GASTADOS` INT NOT NULL DEFAULT 0,
  `REGISTRADO_POR_TAQUILLERO` TINYINT NOT NULL,
  `NOMBRES` VARCHAR(100) NOT NULL,
  `APELLIDOS` VARCHAR(100) NOT NULL,
  `DNI` VARCHAR(8) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `GENERO` ENUM('MASCULINO', 'FEMENINO', 'NINGUNO_DE_LOS_ANTERIORES') NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_USUARIOS1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `ebentos`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`VENTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`VENTA` (
  `VENTA_ID` INT NOT NULL AUTO_INCREMENT,
  `EVENTO_ID` INT NOT NULL,
  `GESTOR_USUARIO_ID` INT NULL,
  `CLIENTE_USUARIO_ID` INT NOT NULL,
  `MONTO_TOTAL_ORIGINAL` DOUBLE NOT NULL,
  `DESCUENTO_TOTAL` DOUBLE NOT NULL,
  `MONTO_TOTAL_FINAL` DOUBLE NOT NULL,
  `REGISTRADO_POR_TAQUILLERO` TINYINT NOT NULL,
  `METODO_PAGO` ENUM('TARJETA_DE_CREDITO', 'YAPE', 'PLIN', 'EFECTIVO') NOT NULL,
  PRIMARY KEY (`VENTA_ID`),
  INDEX `fk_VENTAS_EVENTOS1_idx` (`EVENTO_ID` ASC) VISIBLE,
  INDEX `fk_VENTAS_CLIENTE1_idx` (`CLIENTE_USUARIO_ID` ASC) VISIBLE,
  INDEX `fk_VENTAS_GESTOR1_idx` (`GESTOR_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_VENTAS_EVENTOS1`
    FOREIGN KEY (`EVENTO_ID`)
    REFERENCES `ebentos`.`EVENTO` (`EVENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_USUARIO_ID`)
    REFERENCES `ebentos`.`CLIENTE` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_GESTOR1`
    FOREIGN KEY (`GESTOR_USUARIO_ID`)
    REFERENCES `ebentos`.`GESTOR` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`ENTRADA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`ENTRADA` (
  `ENTRADA_ID` INT NOT NULL AUTO_INCREMENT,
  `VENTA_ID` INT NOT NULL,
  `ZONA_ID` INT NOT NULL,
  `ASIENTO_ID` INT NULL,
  `PRECIO_ORIGINAL` DOUBLE NOT NULL,
  `DESCUENTO` DOUBLE NOT NULL,
  `PRECIO_FINAL` DOUBLE NOT NULL,
  `QR` BLOB NOT NULL,
  PRIMARY KEY (`ENTRADA_ID`),
  INDEX `fk_ENTRADAS_VENTAS1_idx` (`VENTA_ID` ASC) VISIBLE,
  INDEX `fk_ENTRADAS_ASIENTOS1_idx` (`ASIENTO_ID` ASC) VISIBLE,
  INDEX `fk_ENTRADAS_ZONAS1_idx` (`ZONA_ID` ASC) VISIBLE,
  CONSTRAINT `fk_ENTRADAS_VENTAS1`
    FOREIGN KEY (`VENTA_ID`)
    REFERENCES `ebentos`.`VENTA` (`VENTA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTRADAS_ASIENTOS1`
    FOREIGN KEY (`ASIENTO_ID`)
    REFERENCES `ebentos`.`ASIENTO` (`ASIENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTRADAS_ZONAS1`
    FOREIGN KEY (`ZONA_ID`)
    REFERENCES `ebentos`.`ZONA` (`ZONA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`DESCUENTO_X_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`DESCUENTO_X_CLIENTE` (
  `CLIENTE_USUARIO_ID` INT NOT NULL,
  `DESCUENTO_ID` INT NOT NULL,
  PRIMARY KEY (`CLIENTE_USUARIO_ID`, `DESCUENTO_ID`),
  INDEX `fk_CLIENTE_has_PROMOCIONES_PROMOCIONES1_idx` (`DESCUENTO_ID` ASC) VISIBLE,
  INDEX `fk_CLIENTE_has_PROMOCIONES_CLIENTE1_idx` (`CLIENTE_USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_CLIENTE_has_PROMOCIONES_CLIENTE1`
    FOREIGN KEY (`CLIENTE_USUARIO_ID`)
    REFERENCES `ebentos`.`CLIENTE` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CLIENTE_has_PROMOCIONES_PROMOCIONES1`
    FOREIGN KEY (`DESCUENTO_ID`)
    REFERENCES `ebentos`.`DESCUENTO` (`DESCUENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`PRODUCTORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`PRODUCTORA` (
  `USUARIO_ID` INT NOT NULL,
  `RUC` VARCHAR(11) NOT NULL,
  `RAZON_SOCIAL` VARCHAR(60) NOT NULL,
  `NOMBRE_COMERCIAL` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`USUARIO_ID`),
  UNIQUE INDEX `RUC_UNIQUE` (`RUC` ASC) VISIBLE,
  INDEX `fk_PRODUCTORA_USUARIO1_idx` (`USUARIO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUCTORA_USUARIO1`
    FOREIGN KEY (`USUARIO_ID`)
    REFERENCES `ebentos`.`USUARIO` (`USUARIO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ebentos`.`DESCUENTO_X_ZONA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ebentos`.`DESCUENTO_X_ZONA` (
  `DESCUENTO_ID` INT NOT NULL,
  `ZONA_ID` INT NOT NULL,
  PRIMARY KEY (`DESCUENTO_ID`, `ZONA_ID`),
  INDEX `fk_DESCUENTO_has_ZONA_ZONA1_idx` (`ZONA_ID` ASC) VISIBLE,
  INDEX `fk_DESCUENTO_has_ZONA_DESCUENTO1_idx` (`DESCUENTO_ID` ASC) VISIBLE,
  CONSTRAINT `fk_DESCUENTO_has_ZONA_DESCUENTO1`
    FOREIGN KEY (`DESCUENTO_ID`)
    REFERENCES `ebentos`.`DESCUENTO` (`DESCUENTO_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DESCUENTO_has_ZONA_ZONA1`
    FOREIGN KEY (`ZONA_ID`)
    REFERENCES `ebentos`.`ZONA` (`ZONA_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
