INSERT INTO rol (rol_id, nombre)
VALUES
(1, 'CLIENTE'),
(2, 'PRODUCTORA'),
(3, 'GESTOR_LOCAL'),
(4, 'DUENHO_LOCAL'),
(5, 'TAQUILLERO'),
(6, 'ADMIN'),
(7, 'ORGANIZADOR_EVENTOS');

-- Clientes
INSERT INTO usuario(ROL_ID, TELEFONO, EMAIL, CONTRASENHA, ACTIVO, CODIGO_RESETEO, EXPIRACION_CODIGO) values(1, 900000000, 'benny.baca@outlook.com', '$2a$10$rJoVZ9kwharFWvGSL.DH6OTJTxintEvhyKgVcHIEdfeWop87xJC8a', 1, null, null);
INSERT INTO cliente(USUARIO_ID, PUNTOS_ACUMULADOS, PUNTOS_GASTADOS, REGISTRADO_POR_TAQUILLERO, NOMBRES, APELLIDOS, DNI, FECHA_NACIMIENTO, GENERO) values(1, 0, 0, 0, 'Benny', 'Baca Chávez', '85265470', '2025-10-27', 'MASCULINO');

-- Administradores
INSERT INTO usuario(ROL_ID, TELEFONO, EMAIL, CONTRASENHA, ACTIVO, CODIGO_RESETEO, EXPIRACION_CODIGO) values(6, 700000000, 'a20222031@pucp.edu.pe', '$2a$10$76UGt0cZUVnjDH4ZEM8kaOT4oYLb3d.FhrAhnNHawQz8LJL18BBzm', 1, null, null);

-- Departamentos
INSERT INTO DEPARTAMENTO(NOMBRE) VALUES('LIMA');
INSERT INTO DEPARTAMENTO(NOMBRE) VALUES('AREQUIPA');

-- Provincias (Lima – Departamento_ID = 1)
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('LIMA METROPOLITANA', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('BARRANCA', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CAJATAMBO', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CANTA', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CAÑETE', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('HUARAL', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('HUAROCHIRÍ', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('HUAURA', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('OYÓN', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('YAUYOS', 1);

-- Provincias (Arequipa – Departamento_ID = 2)
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('AREQUIPA', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CAMANÁ', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CARAVELÍ', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CASTILLA', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CAYLLOMA', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('CONDESUYOS', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('ISLAY', 2);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('LA UNIÓN', 2);

-- Distritos ejemplares (Provincia_ID según el orden de inserción anterior)

-- Para “LIMA METROPOLITANA” (Provincia_ID = 1)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ANCON', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ATE', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('BARRANCO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('BREÑA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CARABAYLLO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHACLACAYO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHORRILLOS', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CIENEGUILLA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('COMAS', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('EL AGUSTINO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('INDEPENDENCIA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('JESUS MARIA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LA MOLINA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LA VICTORIA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LIMA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LINCE', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LOS OLIVOS', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LURIGANCHO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LURIN', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MAGDALENA DEL MAR', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MIRAFLORES', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PACHACAMAC', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUEBLO LIBRE', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUENTE PIEDRA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUNTA HERMOZA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUNTA NEGRA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('RIMAC', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN BARTOLO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN BORJA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN ISIDRO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN JUAN DE LURIGANCHO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN JUAN DE MIRAFLORES', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN LUIS', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN MARTIN DE PORRES', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN MIGUEL', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SANTA ANITA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SANTA MARIA DEL MAR', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SANTA ROSA', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SANTIAGO DE SURCO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SURQUILLO', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('VILLA EL SALVADOR', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('VILLA MARIA DEL TRIUNFO', 1);

-- Para “BARRANCA” (Provincia_ID = 2)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('BARRANCA', 2);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PARAMONGA', 2);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUNTA NEGRA', 2);

-- Para “CAJATAMBO” (Provincia_ID = 3)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CAJATAMBO', 3);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('COPA', 3);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('GORGOR', 3);

-- Para “CANTA” (Provincia_ID = 4)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CANTA', 4);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('HUAROS', 4);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LACHAQUI', 4);

-- Para “CAÑETE” (Provincia_ID = 5)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN VICTORIA', 5);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('LORETO', 5);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('COAYLLO', 5);

-- Para “HUARAL” (Provincia_ID = 6)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('HUARAL', 6);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ATAVILLOS', 6);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHANCAY', 6);

-- Para “HUAROCHIRÍ” (Provincia_ID = 7)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MATUCANA', 7);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ANTIOQUIA', 7);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('HUAÑEC', 7);

-- For “HUAURA” (Provincia_ID = 8)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('HUACHO', 8);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('VEGUETA', 8);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHECRAS', 8);

-- For “OYÓN” (Provincia_ID = 9)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('OYÓN', 9);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ANDAJES', 9);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('NAVÁN', 9);

-- For “YAUYOS” (Provincia_ID = 10)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('YAUYOS', 10);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('AYAVI', 10);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CATAHUASI', 10);

-- Para “AREQUIPA” (Provincia_ID = 11)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('AREQUIPA', 11);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('YURA', 11);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CERRO COLORADO', 11);

-- Para “CAMANÁ” (Provincia_ID = 12)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CAMANÁ', 12);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('OCOÑA', 12);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('QUILCA', 12);

-- Para “CARAVELÍ” (Provincia_ID = 13)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ACARÍ', 13);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ATICO', 13);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('BELLA UNIÓN', 13);

-- Para “CASTILLA” (Provincia_ID = 14)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('APLAO', 14);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ORCOPAMPA', 14);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('TACNA', 14);

-- Para “CAYLLOMA” (Provincia_ID = 15)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHIVAY', 15);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MADREDE DIOS', 15);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('TUTI', 15);

-- Para “CONDESUYOS” (Provincia_ID = 16)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('CHUQUIBAMBA', 16);
INSERT INTO DISTRTO(NOMBRE,PROVINCIA_ID) VALUES('YANAQUIHUA', 16);
INSERT INTO DISTRTO(NOMBRE,PROVINCIA_ID) VALUES('IRAY', 16);

-- For “ISLAY” (Provincia_ID = 17)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MOLLENDO', 17);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('ISLAY', 17);
INSERT INTO DISTRTO(NOMBRE,PROVINCIA_ID) VALUES('PUNTA DE BOMBÓN', 17);

-- For “LA UNIÓN” (Provincia_ID = 18)
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('COTAHUASI', 18);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('PUYCA', 18);
INSERT INTO DISTRTO(NOMBRE,PROVINCIA_ID) VALUES('TOMEPAMPA', 18);


 
 
