INSERT INTO rol (rol_id, nombre)
VALUES
(1, 'CLIENTE'),
(2, 'PRODUCTORA'),
(3, 'GESTOR_LOCAL'),
(4, 'DUENHO_LOCAL'),
(5, 'TAQUILLERO'),
(6, 'ADMIN'),
(7, 'ORGANIZADOR_EVENTOS');

-- Clientes
INSERT INTO usuario(ROL_ID, TELEFONO, EMAIL, CONTRASENHA, ACTIVO, CODIGO_RESETEO, EXPIRACION_CODIGO) values(1, 900000000, 'benny.baca@outlook.com', '$2a$10$rJoVZ9kwharFWvGSL.DH6OTJTxintEvhyKgVcHIEdfeWop87xJC8a', 1, null, null);
INSERT INTO cliente(USUARIO_ID, PUNTOS_ACUMULADOS, PUNTOS_GASTADOS, REGISTRADO_POR_TAQUILLERO, NOMBRES, APELLIDOS, DNI, FECHA_NACIMIENTO, GENERO) values(1, 0, 0, 0, 'Benny', 'Baca Chávez', '85265470', '2025-10-27', 'MASCULINO');

-- Administradores
INSERT INTO usuario(ROL_ID, TELEFONO, EMAIL, CONTRASENHA, ACTIVO, CODIGO_RESETEO, EXPIRACION_CODIGO) values(6, 700000000, 'a20222031@pucp.edu.pe', '$2a$10$76UGt0cZUVnjDH4ZEM8kaOT4oYLb3d.FhrAhnNHawQz8LJL18BBzm', 1, null, null);

INSERT INTO DEPARTAMENTO(NOMBRE) VALUES('LIMA');
INSERT INTO DEPARTAMENTO(NOMBRE) VALUES('AREQUIPA');

INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('LIMA METROPOLITANA', 1);
INSERT INTO PROVINCIA(NOMBRE,DEPARTAMENTO_ID) VALUES('HUACHO', 1);

INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('MIRAFLORES', 1);
INSERT INTO DISTRITO(NOMBRE,PROVINCIA_ID) VALUES('SAN JUAN DE MIRAFLORES', 1);

INSERT INTO PUNTOVENTA(NOMBRE,DIRECCION,ACTIVO,DISTRITO_ID) VALUES('AAA','AAA', 1, 1);
INSERT INTO PUNTOVENTA(NOMBRE,DIRECCION,ACTIVO,DISTRITO_ID) VALUES('BBB','BBB', 1, 2);